language: java
jdk:
- openjdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
after_success:
- mvn clean cobertura:cobertura coveralls:report
env:
  global:
    secure: nUyxAiCRV60rKxKa1OeBFlYopCAV9yiUnr8bFBVSurDmzsgP+rOsUDOE3GN0PAHBV9QId+i2bNk7JGM29RRVhKXzYD92d55Aa+b1d2C71/+UUJeaMi30Wa+tEY3v+ddQI4RFqqFl4IJmqN7kcjOUmRjmLHRa2KILgk3EnbpMXqggr71P2cOcedOneuYOXY1JACrqV46ZFTUSqIS8E+OLxGUyGRAtKcETcLHItHHC2MOfpYVc/hNnFev8XdtVo2fOmXe3MeTxsI4x6PcsdA2fzxbHfvuqk5lZvA/+/GOh9Nx0IO1UdbdzMa1MjOw23y1eHjSvqo2emYLtYeDrNOygC2NoqtID5kL0nhf6rs1gKFn1AZyb7xbxSVCfu2n/IOfqpIKhRTDYByjABLCILs0C/J+dQJOixs9PDYEW2MzRpr0KPY6sDSsHbz+o54xxo7xCXBvwIQKDSDIED54Z/EhqW6NDUmUK2oyHac+lu/X8Z/IhLzlMVXiH1TcL/+mSPr4ZYAEpxr8F24aqhdaAEV+h7h4qt+4cxPJKpf6J8zgAfgLJyIK9kGBdRBlPZOR1xtRcwWgQat4jvUfEnAlr5/RjnbZ/9YN51l85aBkb91jTeknm7U15FgULJe+Q58UT2zxdg8IH1s7yhWVZXdTZU1+kxK5HSlojJ1LgU89jAbjUIj0=
